namespace Jodre11.EnumerateImplementations;

using Microsoft.CodeAnalysis;

[Generator]
public class EnumerateImplementationsGenerator : ISourceGenerator
{
    public void Initialize(GeneratorInitializationContext context)
    {
        // No initialization required for this one yet.
    }

    public void Execute(GeneratorExecutionContext context)
    {
        var mainMethod = context.Compilation.GetEntryPoint(context.CancellationToken);
        var typeName = mainMethod?.ContainingType.Name ?? "EnumerateImplementations";
        
        var source = $$"""
                    // <auto-generated/>
                    namespace {{mainMethod?.ContainingNamespace.ToDisplayString() ?? "Jodre11.EnumerateImplementations.Generated"}}
                    {
                        using System;
                        
                        public static partial class {{typeName}}
                        {
                            static partial void HelloFrom(string name) =>
                            Console.WriteLine($"Generator says: Hi from '{name}'");
                        }
                    }
                    """;
        
        context.AddSource($"{typeName}.g.cs", source);
    }
}
